content:
  - name: books
    label: Reading list
    type: file
    path: books.md
    format: raw
    fields:
      - name: body
        label: Reading list
        type: rich-text
        options:
          format: markdown
          media: false
